title:              Jhonattan Lino
email:              jhonattanlino@pucpr.edu.br
description:        Machine learning for finance
author:             Jhonattan Lino
baseurl:            ""
url:                "https://jhonattanln.github.io"

# Social Profiles
twitter_username:   lino_jhonattan
github_username:    Jhonattanln
facebook_username:  
instagram_username:  
linkedin_username:  /jhonattan-economia/

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-7GG3T4HSPS # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
highlighter: rouge